### PR TITLE
Responsive About Us page

### PR DESCRIPTION
**Pull request by JuanitaCathy**
Created a responsive About Us page at index.html.

### CODE REVIEW

**Comment by jzf21** [comment]
Please do no change index.html. revert changes and add it /components/About

**Review by jzf21 — COMMENTED** [review]
Do not change index.html in react.

**Comment by JuanitaCathy** [comment]
@jzf21 please review, thanks

**Review by jzf21 — CHANGES_REQUESTED** [review]
image
Please create a styles.css file in the directory and paste your css code there and link it to the jsx page.
you have only styled the heading the about page should have minimum width of 100vh

**Pull request closed without merging**
