### PR TITLE
Made navbar logo and menu icon responsive

### LINKED ISSUE #3: Logo and Hamburger menu is not responsive in small devices.
The logo and hamburger menu icon are not responsive on small devices, they appear side by side in the center of the screen.
Screenshot 2023-10-01 at 12 40 17 PM

### PR DESCRIPTION
**Pull request by akssshh**
This PR resolves #3 issue

Made Navbar logo and hamburger icon responsive for smaller devices.
Screenshot 2023-10-01 at 3 20 39 PM

### CODE REVIEW

**Comment by jzf21** [comment]
image

It messed up the desktop view now .

**Comment by akssshh** [comment]
> image
> 
> It messed up the desktop view now .

i'll check and make another PR soon!

**Comment by akssshh** [comment]
Is it Ok?? @jzf21 
<br>
Screenshot 2023-10-01 at 9 43 39 PM

<br>
<br>

Screenshot 2023-10-01 at 9 39 56 PM

**Comment by jzf21** [comment]
Have merged

**Pull request merged**
